// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpleSurveys.Data.Configuration;

#nullable disable

namespace SimpleSurveys.Data.Migrations
{
    [DbContext(typeof(SimpleSurveysContext))]
    partial class SimpleSurveysContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CheckResultValue", b =>
                {
                    b.Property<int>("CheckResultsID")
                        .HasColumnType("integer");

                    b.Property<int>("ValuesID")
                        .HasColumnType("integer");

                    b.HasKey("CheckResultsID", "ValuesID");

                    b.HasIndex("ValuesID");

                    b.ToTable("CheckResultValue");
                });

            modelBuilder.Entity("CheckValue", b =>
                {
                    b.Property<int>("ChecksID")
                        .HasColumnType("integer");

                    b.Property<int>("ValuesID")
                        .HasColumnType("integer");

                    b.HasKey("ChecksID", "ValuesID");

                    b.HasIndex("ValuesID");

                    b.ToTable("CheckValue");
                });

            modelBuilder.Entity("DropDownResultValue", b =>
                {
                    b.Property<int>("DropDownResultsID")
                        .HasColumnType("integer");

                    b.Property<int>("ValuesID")
                        .HasColumnType("integer");

                    b.HasKey("DropDownResultsID", "ValuesID");

                    b.HasIndex("ValuesID");

                    b.ToTable("DropDownResultValue");
                });

            modelBuilder.Entity("DropDownValue", b =>
                {
                    b.Property<int>("DropDownsID")
                        .HasColumnType("integer");

                    b.Property<int>("ValuesID")
                        .HasColumnType("integer");

                    b.HasKey("DropDownsID", "ValuesID");

                    b.HasIndex("ValuesID");

                    b.ToTable("DropDownValue");
                });

            modelBuilder.Entity("RadioValue", b =>
                {
                    b.Property<int>("RadiosID")
                        .HasColumnType("integer");

                    b.Property<int>("ValuesID")
                        .HasColumnType("integer");

                    b.HasKey("RadiosID", "ValuesID");

                    b.HasIndex("ValuesID");

                    b.ToTable("RadioValue");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Step", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<int>("SurveyID")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("SurveyID");

                    b.ToTable("Steps");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Step");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.StepResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("StepID")
                        .HasColumnType("integer");

                    b.Property<int>("SurveyResultID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("StepID");

                    b.HasIndex("SurveyResultID");

                    b.ToTable("StepResults");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StepResult");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Survey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ClosedSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("MaxSubmissions")
                        .HasColumnType("integer");

                    b.Property<bool>("Open")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<bool>("Public")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.SurveyResult", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("Submitted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SurveyID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("SurveyID");

                    b.ToTable("SurveyResults");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Value", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Check", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.Step");

                    b.HasDiscriminator().HasValue("Check");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Date", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.Step");

                    b.Property<DateTime?>("Default")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Placeholder")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Placeholder");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("DateType");

                    b.ToTable("Steps", t =>
                        {
                            t.Property("Default")
                                .HasColumnName("Date_Default");
                        });

                    b.HasDiscriminator().HasValue("Date");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.DropDown", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.Step");

                    b.Property<int?>("Default")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Default");

                    b.Property<bool>("MultiSelect")
                        .HasColumnType("boolean");

                    b.Property<string>("Placeholder")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Placeholder");

                    b.HasDiscriminator().HasValue("DropDown");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Number", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.Step");

                    b.Property<int?>("Default")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Default");

                    b.Property<string>("Placeholder")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Placeholder");

                    b.HasDiscriminator().HasValue("Number");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Radio", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.Step");

                    b.HasDiscriminator().HasValue("Radio");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Range", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.Step");

                    b.Property<int>("Max")
                        .HasColumnType("integer");

                    b.Property<int>("Min")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Range");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Text", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.Step");

                    b.Property<string>("Placeholder")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("Placeholder");

                    b.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.YesNo", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.Step");

                    b.HasDiscriminator().HasValue("YesNo");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.CheckResult", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.StepResult");

                    b.HasDiscriminator().HasValue("CheckResult");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.DateResult", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.StepResult");

                    b.Property<DateTime>("Value")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateTime_Value");

                    b.HasDiscriminator().HasValue("DateResult");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.DropDownResult", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.StepResult");

                    b.HasDiscriminator().HasValue("DropDownResult");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.NumberResult", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.StepResult");

                    b.Property<int>("Value")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Int_Value");

                    b.HasDiscriminator().HasValue("NumberResult");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.RadioResult", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.StepResult");

                    b.Property<int>("ValueID")
                        .HasColumnType("integer");

                    b.HasIndex("ValueID");

                    b.HasDiscriminator().HasValue("RadioResult");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.RangeResult", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.StepResult");

                    b.Property<int>("Value")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("Int_Value");

                    b.HasDiscriminator().HasValue("RangeResult");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.RateResult", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.StepResult");

                    b.Property<string>("Value")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("String_Value");

                    b.HasDiscriminator().HasValue("RateResult");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.TextResult", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.StepResult");

                    b.Property<string>("Value")
                        .IsRequired()
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("text")
                        .HasColumnName("String_Value");

                    b.HasDiscriminator().HasValue("TextResult");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.YesNoResult", b =>
                {
                    b.HasBaseType("SimpleSurveys.Data.Models.StepResult");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean")
                        .HasColumnName("Bool_Value");

                    b.HasDiscriminator().HasValue("YesNoResult");
                });

            modelBuilder.Entity("CheckResultValue", b =>
                {
                    b.HasOne("SimpleSurveys.Data.Models.CheckResult", null)
                        .WithMany()
                        .HasForeignKey("CheckResultsID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleSurveys.Data.Models.Value", null)
                        .WithMany()
                        .HasForeignKey("ValuesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CheckValue", b =>
                {
                    b.HasOne("SimpleSurveys.Data.Models.Check", null)
                        .WithMany()
                        .HasForeignKey("ChecksID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleSurveys.Data.Models.Value", null)
                        .WithMany()
                        .HasForeignKey("ValuesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DropDownResultValue", b =>
                {
                    b.HasOne("SimpleSurveys.Data.Models.DropDownResult", null)
                        .WithMany()
                        .HasForeignKey("DropDownResultsID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleSurveys.Data.Models.Value", null)
                        .WithMany()
                        .HasForeignKey("ValuesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DropDownValue", b =>
                {
                    b.HasOne("SimpleSurveys.Data.Models.DropDown", null)
                        .WithMany()
                        .HasForeignKey("DropDownsID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleSurveys.Data.Models.Value", null)
                        .WithMany()
                        .HasForeignKey("ValuesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RadioValue", b =>
                {
                    b.HasOne("SimpleSurveys.Data.Models.Radio", null)
                        .WithMany()
                        .HasForeignKey("RadiosID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleSurveys.Data.Models.Value", null)
                        .WithMany()
                        .HasForeignKey("ValuesID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Step", b =>
                {
                    b.HasOne("SimpleSurveys.Data.Models.Survey", "Survey")
                        .WithMany("Steps")
                        .HasForeignKey("SurveyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.StepResult", b =>
                {
                    b.HasOne("SimpleSurveys.Data.Models.Step", "Step")
                        .WithMany("Results")
                        .HasForeignKey("StepID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleSurveys.Data.Models.SurveyResult", "SurveyResult")
                        .WithMany("StepResults")
                        .HasForeignKey("SurveyResultID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Step");

                    b.Navigation("SurveyResult");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.SurveyResult", b =>
                {
                    b.HasOne("SimpleSurveys.Data.Models.Survey", "Survey")
                        .WithMany("SurveyResults")
                        .HasForeignKey("SurveyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.RadioResult", b =>
                {
                    b.HasOne("SimpleSurveys.Data.Models.Value", "Value")
                        .WithMany("RadioResults")
                        .HasForeignKey("ValueID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Value");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Step", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Survey", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("SurveyResults");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.SurveyResult", b =>
                {
                    b.Navigation("StepResults");
                });

            modelBuilder.Entity("SimpleSurveys.Data.Models.Value", b =>
                {
                    b.Navigation("RadioResults");
                });
#pragma warning restore 612, 618
        }
    }
}
